main: com.github.Paidyy.deathheaddrop.Maino
name: DeathHeadDrop
version: 1.2
author: Paidyy
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  deathheaddrop:
   description: DeathHeadDrop Info and Etc
   permission: deathheaddrop.main
   
permissions:
  deathheaddrop.main:
   default: true
  deathheaddrop.drop_head:
   default: true
  deathheaddrop.reload:
   default: op
  deathheaddrop.*:
   default: op
   children:
    deathheaddrop.main: true
    deathheaddrop.drop_head: true
    deathheaddrop.reload: true